services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning --user evident on >evident ~* +@all
    security_opt:
      - no-new-privileges:false
    volumes:
      - redis-data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis-data: