export const carriers = [
  {
    companyId: "29806de0-b0b5-406d-968d-229d7b79d238",
    createdBy: "cdbXywsuB10HSjagAJ1xSeREea6l7GAs",

    name: "LongIslandCityLtd - Evident",
    type: "FEDEX" as const,
    shipperPhone: "07415070411",
    credentialType: "BEARER" as const,
    credentials: {
      clientId: "l7ce8fefbb5e7344d285f93dbd84569d4f",

      clientSecret: "3d377a2446d944238a13cb6bde8806b3",
    },
    isActive: true,
    isDefault: false,
    addressLine1: "CANVEYISLANDSS80EQ",
    addressLine2: "Unit10, Thamesview130",
    accountNumber: "802255209",
    shipperName: "LongIslandCityLtd",
    shipperEmail: "longisland@example.com",
    countryCode: "GB",
    city: "CANVEYISLAND",
    postalCode: "SS80EQ",
    stateOrProvinceCode: "GB",
    updatedBy: null,
    metadata: {
      pickupType: "DROPOFF_AT_FEDEX_LOCATION",
      serviceType: "FEDEX_GROUND",
      packagingType: "YOUR_PACKAGING",
    },
  },
  {
    companyId: "29806de0-b0b5-406d-968d-229d7b79d238",
    createdBy: "cdbXywsuB10HSjagAJ1xSeREea6l7GAs",
    name: "DHL TEST 2",
    type: "DHL" as const,
    shipperPhone: "+49 123456789",
    credentialType: "BEARER" as const,
    credentials: {
      username: "user-valid",
      password: "SandboxPasswort2023!",
    },
    isActive: true,
    isDefault: false,
    addressLine1: "Kurt-Schumacher-Str. 20",
    addressLine2: null,
    accountNumber: "",
    shipperName: "Evident DHL",
    shipperEmail: "longisland@example.com",
    countryCode: "DEU",
    city: "Bonn",
    postalCode: "53113",
    stateOrProvinceCode: null,

    updatedBy: null,
    metadata: {
      billingNumber: "33333333330102",
    },
  },
  {
    companyId: "29806de0-b0b5-406d-968d-229d7b79d238",
    createdBy: "cdbXywsuB10HSjagAJ1xSeREea6l7GAs",
    name: "Uk Amazon sandbox",
    type: "AMAZON" as const,
    shipperPhone: "09090re9w8e0r",
    credentialType: "BEARER" as const,
    credentials: {
      refreshToken:
        "Atzr|IwEBIOeIsxJYF8DULJRb-0nEFJnlLHFSEDdQOm7bKekmrZZ-hiTbFahVE-2ilMjWxL10iQjl_eA3mJY7LhvjBMjrEqlKBc0oQociKfMsK7hM7BDqn9Y5rwTeKu-ObMPzyKaK4gre228Zw4AORI-LQHds-SMIYViSW5jH6Qbg5Pfv72Csnu1Q6nt6MEN2fU7g3U01FSSGBdg0MBfuCFJ4zCL20Mfevs8ORmxdWtD9Y3M18xGjGx4Q7SG5r_3faTVtwUvwwN3qlVaOO8qhPHZkP2d38n1sQaim9X4_ThkNretwN0a_gT99VslMGD6wCq-aR2UZDwo",
    },
    isActive: true,
    isDefault: true,
    addressLine1: "UNIT 10 ESTUARY HOUSE, THAMESVIEW BUSINESS PARK",
    addressLine2: null,
    accountNumber: null,
    shipperName: "ROUGH AND TOUGH-ESTUARY HOUSE",
    shipperEmail: "roughandtough@gmail.com",
    countryCode: "GB",
    city: "CANVEY ISLAND, Essex",
    postalCode: "SS8 OEQ",
    stateOrProvinceCode: "ENG",
    metadata: {
      storeId: "1234",
    },
  },
  {
    companyId: "29806de0-b0b5-406d-968d-229d7b79d238",
    createdBy: "cdbXywsuB10HSjagAJ1xSeREea6l7GAs",

    name: "Long Island City Ltd Live Account",
    type: "ROYAL_MAIL" as const,
    shipperPhone: "23829387912873",
    credentialType: "BEARER" as const,
    credentials: {
      authKey: "0f0cbff6-786f-49e6-910a-5125bcf4bc00",
    },
    isActive: true,
    isDefault: true,
    addressLine1: null,
    addressLine2: null,
    accountNumber: null,
    shipperName: "Long Island City Ltd",
    shipperEmail: "ashourov@evidentbd.com",
    countryCode: "GB",
    city: null,
    postalCode: null,
    stateOrProvinceCode: null,
    updatedBy: null,
    metadata: {},
  },
]
